version: '2'
services:
    api:
        build: .
        ports:
            - "4000:4000"

    pactverifier:
        image: dius/pact-provider-verifier-docker
        links:
            - api:api
        volumes:
            - ./pact/pacts:/tmp/pacts
        environment:
            # - pact_urls=/tmp/pacts/another-they.json,/tmp/pacts/fail.json,/tmp/pacts/me-they.json ## Run all files
            - pact_urls=/tmp/pacts/another-they.json
            - provider_base_url=http://api:4000
            - provider_states_url=http://api:4000/provider-states
            - provider_states_active_url=http://api:4000/provider-state
